import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Viewport } from "next";
import Header from "@/components/header";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ZenioTech",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
initialScale: 1,
    width: 'device-width'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <meta
  name="viewport"
  content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
/>
      <body suppressHydrationWarning 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Header />
        {children}
        <div className=" flex items-end my-18 "> <Footer /></div>
       
      </body>
    </html>
  );
}
